# Generated by Django 5.0 on 2023-12-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_string', models.CharField(max_length=30, verbose_name='секретная строка')),
                ('code_phrase', models.CharField(max_length=70, verbose_name='кодовая фраза')),
                ('secret_key', models.CharField(blank=True, max_length=70, null=True, verbose_name='секретный ключ')),
                ('counter', models.IntegerField(default=0, verbose_name='счетчик')),
            ],
            options={
                'verbose_name': 'секрет',
                'verbose_name_plural': 'секреты',
            },
        ),
    ]
